### ISSUE TITLE
ErrorException In Grid.php line 279

### ISSUE THREAD

**Issue by celaraze** [xiaoxuan6/laravel-admin-grid#1]
我在控制器中把
use Encore\Admin\Grid;
改为:
use James\Admin\Grid;

没有其它任何变动,报错:
ErrorException In Grid.php line 279
Undefined index: useActions

**Comment by shmilylbelva** [comment]
同问

**Comment by xiaoxuan6** [comment]
laravel-admin 版本过高导致，将 `laravel-admin-grid` 跟新到 1.2.0 版本

**Comment by celaraze** [comment]
确认解决
